research_event_task:
  description: >
    Use event tool to get user events from user's calendar 
    The goal is to prepare enough information to make an informed analysis of the user's events.
    You should also give insights about how to improve the schedule of that day
  expected_output: >
    A list of the current schedule and another list of suggestions to improve user's schedule.

analyze_company_task:
  description: >
    Take {company_name}'s financial information, analyze it, and provide a financial analysis, including: Profitability ratio,
    Liquidity ratios, Solvency ratios, Efficiency ratios, Growth metrics, Valuation metrics, and Cash flow metrics.
  expected_output: >
    A nicely formatted analysis including all of the financial metrics necessary for a thorough financial analysis of a company.
    Also this report should include all the recent data like stock price, yield rate
